interval: 5s
timeout: 5s

server:
  port: 8080
  read_header_timeout: 3s
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 15s

storage:
  retention_hours: 12

logger:
  level: "debug"
  format: "json"
